--  Schema definition
CREATE TYPE "image_type" AS ENUM (
  'logo',
  'cover',
  'gallery',
  'menu'
);

CREATE TYPE "stock_update_mode" AS ENUM (
  'manual',
  'automatic',
  'integrated_pos'
);

CREATE TYPE "proposal_status" AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TABLE business_categories (
  id INT PRIMARY KEY,
  category VARCHAR NOT NULL,
  description TEXT,
  parent_category_id INT REFERENCES business_categories(id),
  svg TEXT
);

CREATE TABLE "businesses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "category_id" int,
  "is_verified" bool DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "business_locations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_id" int,
  "location"  GEOGRAPHY(POINT, 4326), -- PostGIS point, 
  "location_name" varchar,
  "location_index" smallint,
  "is_public" bool DEFAULT true
);

CREATE TABLE "business_features" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature" varchar,
  "description" text,
  "svg" text
);

CREATE TABLE "business_feature_proposals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_id" int,
  "feature_id" int,
  "feature_score" int DEFAULT 0,
  "proposal_status" proposal_status DEFAULT 'pending'
);

CREATE TABLE "business_location_opening_hours" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location_id" int,
  "day_of_week" int,
  "open_time" time,
  "close_time" time,
  "is_closed" bool DEFAULT false
);

CREATE TABLE "business_web_links" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_id" int UNIQUE,
  "primary_website_url" varchar,
  "x_url" varchar,
  "facebook_url" varchar,
  "instagram_url" varchar,
  "tiktok_url" varchar
);

CREATE TABLE "business_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_id" int,
  "image_type" image_type,
  "image_index" int,
  "url" varchar
);

CREATE TABLE "business_products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_id" int,
  "product" varchar,
  "description" text,
  "price_gbp" float
);

CREATE TABLE "business_product_stock" (
  "product_id" int PRIMARY KEY,
  "stock_count" int,
  "stock_last_updated" timestamp,
  "stock_update_mode" stock_update_mode
);

CREATE TABLE "customers" (
  "id" uuid PRIMARY KEY,
  "full_name" varchar,
  "email" varchar UNIQUE,
  "avatar_url" varchar,
  "created_at" timestamp
);

COMMENT ON COLUMN "business_locations"."location_index" IS '1: Primary, 2: Secondary';

COMMENT ON COLUMN "business_location_opening_hours"."day_of_week" IS '0=Sun, 1=Mon, ..., 6=Sat';

ALTER TABLE "businesses" ADD FOREIGN KEY ("category_id") REFERENCES "business_categories" ("id");

ALTER TABLE "business_locations" ADD FOREIGN KEY ("business_id") REFERENCES "businesses" ("id");

ALTER TABLE "business_feature_proposals" ADD FOREIGN KEY ("business_id") REFERENCES "businesses" ("id");

ALTER TABLE "business_feature_proposals" ADD FOREIGN KEY ("feature_id") REFERENCES "business_features" ("id");

ALTER TABLE "business_location_opening_hours" ADD FOREIGN KEY ("location_id") REFERENCES "business_locations" ("id");

ALTER TABLE "business_web_links" ADD FOREIGN KEY ("business_id") REFERENCES "businesses" ("id");

ALTER TABLE "business_images" ADD FOREIGN KEY ("business_id") REFERENCES "businesses" ("id");

ALTER TABLE "business_products" ADD FOREIGN KEY ("business_id") REFERENCES "businesses" ("id");

ALTER TABLE "business_product_stock" ADD FOREIGN KEY ("product_id") REFERENCES "business_products" ("id");